version: '3.1'
services:
   maria_db:
      image: mariadb:10.4.17
      command: --default-authentication-plugin=mysql_native_password
#      command: --init-file /data/application/init.sql
#      command: "mysql -uroot -psecret < /data/application/init.sql"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: exporterhub
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
      volumes:
#         - ./db_data:/var/lib/mysql/data
         - ./db_data:/var/lib/mysql/
#         - ./exporterhub_schema.sql:/data/application/init.sql
   scheduler:
      image: nexclipper/exporterhub-api:release-api0.2
      environment:
        APP_DB_ENGINE: django.db.backends.mysql
        DB_NAME: exporterhub
        DB_USER: root
        DB_PASSWORD: secret
        DB_HOST: maria_db
        DB_PORT: "3306"
        APP_STAT: "scheduler"
        SECRET_KEY: "supersecretkey"
        APP_TOKEN: "TOKEN must be HERE!!!"
   api:
      image: nexclipper/exporterhub-api:release-api0.2
      ports:
         - "8000:8000"
      environment:
        APP_DB_ENGINE: django.db.backends.mysql
        DB_NAME: exporterhub
        DB_USER: root
        DB_PASSWORD: secret
        DB_HOST: maria_db
        DB_PORT: "3306"
        SECRET_KEY: "supersecretkey"
        APP_TOKEN: "TOKEN must be HERE!!!"
        APP_STAT: "server"
      depends_on:
         - maria_db
