version: '3.1'
services:
   maria_db:
      image: mariadb:10.4.17
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: "expoterhubpw"
      volumes:
         - ./db_data:/var/lib/mysql/data
   api:
      image: nexclipper/exporterhub-be:0.1
      ports:
         - "8000:8000"
      environment:
        ENGINE: django.db.backends.mysql
        NAME: exporterhub
        USER: root
        PASSWORD: 'expoterhubpw'
        HOST: maria_db
        PORT: "3306"
        SECRET_KEY: "supersecretkey"
      depends_on:
         - maria_db

